# Generated by Django 5.1.1 on 2024-11-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyCarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
                (
                    "work_status_mon",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_tue",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_wed",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_thu",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_fri",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_sat",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                (
                    "work_status_sun",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")], default=1
                    ),
                ),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                ("work4_start_time", models.TimeField(blank=True, null=True)),
                ("work4_end_time", models.TimeField(blank=True, null=True)),
                (
                    "lunch",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "有り(注文)"), (1, "有り(持参)"), (2, "無し")],
                        null=True,
                    ),
                ),
                ("eat_lunch_at", models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkPlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("area", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("order", models.IntegerField()),
                (
                    "morning_transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "送迎"),
                            (1, "車"),
                            (2, "バス"),
                            (3, "自転車"),
                            (4, "徒歩"),
                            (5, "バイク"),
                            (6, "その他"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "pickup_place",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                (
                    "return_transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "送迎"),
                            (1, "車"),
                            (2, "バス"),
                            (3, "自転車"),
                            (4, "徒歩"),
                            (5, "バイク"),
                            (6, "その他"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "dropoff_place",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dropoff_time", models.TimeField(blank=True, null=True)),
                (
                    "work_status_mon",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_tue",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_wed",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_thu",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_fri",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_sat",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                (
                    "work_status_sun",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], default=2
                    ),
                ),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                ("work4_start_time", models.TimeField(blank=True, null=True)),
                ("work4_end_time", models.TimeField(blank=True, null=True)),
                (
                    "lunch",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "有り(注文)"), (1, "有り(持参)"), (2, "無し")],
                        null=True,
                    ),
                ),
                ("eat_lunch_at", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "dropoff_car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropoff_car",
                        to="baseapp.companycarmodel",
                    ),
                ),
                (
                    "pickup_car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_car",
                        to="baseapp.companycarmodel",
                    ),
                ),
                (
                    "dropoff_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropoff_staff",
                        to="baseapp.staffmodel",
                    ),
                ),
                (
                    "pickup_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_staff",
                        to="baseapp.staffmodel",
                    ),
                ),
                (
                    "work1_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_work1_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work2_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_work2_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work3_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_work3_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work4_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_work4_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staffmodel",
            name="work1_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_work1_place",
                to="baseapp.workplacemodel",
            ),
        ),
        migrations.AddField(
            model_name="staffmodel",
            name="work2_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_work2_place",
                to="baseapp.workplacemodel",
            ),
        ),
        migrations.AddField(
            model_name="staffmodel",
            name="work3_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_work3_place",
                to="baseapp.workplacemodel",
            ),
        ),
        migrations.AddField(
            model_name="staffmodel",
            name="work4_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_work4_place",
                to="baseapp.workplacemodel",
            ),
        ),
        migrations.CreateModel(
            name="StaffWorkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(blank=True, max_length=20, null=True)),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "出勤"), (1, "欠勤"), (2, "有給")],
                        null=True,
                    ),
                ),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                ("work4_start_time", models.TimeField(blank=True, null=True)),
                ("work4_end_time", models.TimeField(blank=True, null=True)),
                (
                    "lunch",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "有り(注文)"), (1, "有り(持参)"), (2, "無し")],
                        null=True,
                    ),
                ),
                ("eat_lunch_at", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="baseapp.staffmodel",
                    ),
                ),
                (
                    "work1_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work1_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work2_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work2_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work3_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work3_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work4_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_w_work4_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="CustomerWorkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("work_date", models.DateField()),
                (
                    "work_status",
                    models.IntegerField(
                        choices=[(0, "通所"), (1, "在宅"), (2, "欠席")], null=True
                    ),
                ),
                ("current_status", models.IntegerField(default=0)),
                (
                    "morning_transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "送迎"),
                            (1, "車"),
                            (2, "バス"),
                            (3, "自転車"),
                            (4, "徒歩"),
                            (5, "バイク"),
                            (6, "その他"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "pickup_place",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                (
                    "return_transport_means",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "送迎"),
                            (1, "車"),
                            (2, "バス"),
                            (3, "自転車"),
                            (4, "徒歩"),
                            (5, "バイク"),
                            (6, "その他"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "dropoff_place",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dropoff_time", models.TimeField(blank=True, null=True)),
                ("work1_start_time", models.TimeField(blank=True, null=True)),
                ("work1_end_time", models.TimeField(blank=True, null=True)),
                ("work2_start_time", models.TimeField(blank=True, null=True)),
                ("work2_end_time", models.TimeField(blank=True, null=True)),
                ("work3_start_time", models.TimeField(blank=True, null=True)),
                ("work3_end_time", models.TimeField(blank=True, null=True)),
                ("work4_start_time", models.TimeField(blank=True, null=True)),
                ("work4_end_time", models.TimeField(blank=True, null=True)),
                (
                    "lunch",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "有り(注文)"), (1, "有り(持参)"), (2, "無し")],
                        null=True,
                    ),
                ),
                ("eat_lunch_at", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="baseapp.customermodel",
                    ),
                ),
                (
                    "dropoff_car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_dropoff_car",
                        to="baseapp.companycarmodel",
                    ),
                ),
                (
                    "pickup_car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_pickup_car",
                        to="baseapp.companycarmodel",
                    ),
                ),
                (
                    "dropoff_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_dropoff_staff",
                        to="baseapp.staffmodel",
                    ),
                ),
                (
                    "pickup_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_pickup_staff",
                        to="baseapp.staffmodel",
                    ),
                ),
                (
                    "work1_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_w_work1_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work2_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_w_work2_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work3_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_w_work3_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
                (
                    "work4_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_w_work4_place",
                        to="baseapp.workplacemodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "work_date")},
            },
        ),
    ]
